### ISSUE TITLE
Face Reenactment

### ISSUE THREAD

**Issue by alasokolova** [USTC3DV/FlashAvatar-code#10]
Could you please explain (or ideally upload the scripts) how to apply FlashAvatar for face reenactment task?

Should I train FlashAvatar on source head, run tracking on the target head, and then in `test.py` use `viewpoints` obtained from target and gaussians from the trained FlashAvatar? 
I am a bit confused with the pipeline, so would be happy if you upload the reenactment script.

Thanks in advance!

**Comment by xiangjun-xj** [comment]
For face reenactment, you need to use relative expression transfer because the expression and shape are not well disentangled in FLAME tracking. 
You can take a look at [NeRFace](https://github.com/gafniguy/4D-Facial-Avatars/blob/f687d3be0b15dc7bdcae0a31cf8935987af6863e/nerface_code/nerf-pytorch/real_to_nerf.py#L592) to see how it is done.
